substitutions:
  device_name: berbel-esp32c3
  friendly_name: "Berbel ESP32-C3"

packages:
  base: !include ../berbel_esp32.yaml

esphome:
  name: ${device_name}
  friendly_name: ${friendly_name}
  platform: ESP32
  board: esp32-c3-devkitm-1
  framework:
    type: arduino
    version: latest
