substitutions:
  device_name: berbel-esp32s3
  friendly_name: "Berbel ESP32-S3"

packages:
  base: !include ../berbel_esp32.yaml

esphome:
  name: ${device_name}
  friendly_name: ${friendly_name}
  platform: ESP32
  board: esp32-s3-devkitc-1
  framework:
    type: arduino
    version: latest
  platformio_options:
    board_upload.maximum_ram_size: 327680
    board_upload.maximum_size: 16777216
