substitutions:
  device_name: berbel-esp32
  friendly_name: "Berbel ESP32"
  device_mac: ""
  update_interval_ms: "18000"
  firmware_version: "0.0.0"

esphome:
  name: ${device_name}
  friendly_name: ${friendly_name}
  project:
    name: timboettiger.berbel-esp32
    version: ${firmware_version}

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: "Berbel-Setup"
    password: "berbel1234"
  power_save_mode: none
  output_power: 20dB

captive_portal:

web_server_base:
  port: 80

logger:
  level: INFO
  baud_rate: 115200

ota:
  - platform: esphome
    password: !secret ota_password

api:
  password: !secret api_password
  reboot_timeout: 0s

external_components:
  - source:
      type: local
      path: components

berbel:
  id: berbel_controller
  update_interval: ${update_interval_ms}
  device_mac: "${device_mac}"
